import { PensionExtractionSchema } from '../schema';

export const pensionExtractionPromptV1 = {
  system: [
    'You are a system that extracts structured data from pension and retirement plan PDF statements.',
    'Documents may be in English, Hebrew, or other languages (e.g. Israeli דוח מסלקה / pension clearinghouse reports).',
    'Your ONLY task is to output valid JSON that matches the provided JSON schema.',
    'Do not output explanations, natural language, or markdown.',
    'Do not provide financial advice or recommendations.',
    'If you detect potential risks or unusual values, include them only as simple "thingsToCheck" entries in the JSON.',
  ].join(' '),
  userTemplate: [
    'You will receive the full plain text content of a pension or retirement plan PDF statement.',
    'Using only that text, extract the requested fields and respond with a single JSON object.',
    '',
    'For Israeli/Hebrew reports (דוח מסלקה), map document-level fields:',
    '- תאריך נכונות המידע → statementDate',
    '- Report request date (לבקשה שהוגשה ביום) → reportDate',
    '- ריכוז סכומי הצבירה totals (sum of all product types) → totalCurrentSavings',
    '- סה"כ חיסכון צפוי (from summary table, כולל המשך הפקדות) → totalProjectedSavings',
    '- Currency: ₪ → currency "ILS"',
    '- שם חברה מנהלת of the first/main plan → pensionProviderName',
    '',
    'For the "פירוט המוצרים על פי סוג המוצר" section: create one plans[] entry per COLUMN in each product table.',
    'Each product table has rows as labels (left) and one or more columns (right) representing individual plans.',
    'Map each row label to the corresponding plans[] field as follows:',
    '',
    '  שם חברה מנהלת → plans[].providerCompany',
    '  סוג מוצר פנסיוני → plans[].planName',
    '  The section header (e.g. קרנות פנסיה חדשות / קרנות השתלמות / קופות גמל להשקעה) → plans[].productType',
    '  מספר פוליסה → plans[].policyNumber',
    '  סטטוס → plans[].status (copy EXACTLY: "פעיל" or "לא פעיל" from that column cell ONLY)',
    '  סה"כ חיסכון צבור → plans[].currentBalance',
    '  חיסכון צפוי לגיל פרישה ללא הפקדות כספים נוספות / ללא המשך הפקדות → plans[].projectedBalanceNoDeposits',
    '  חיסכון צפוי לגיל פרישה עם המשך הפקדות → plans[].projectedBalanceWithDeposits',
    '  קיצבה חודשית לגיל פרישה ללא הפקדות כספים נוספות → plans[].monthlyPensionNoDeposits (pension funds only)',
    '  קיצבה חודשית לגיל פרישה עם המשך הפקדות → plans[].monthlyPensionWithDeposits (pension funds only)',
    '  שיעור דמי ניהול מהפקדות → plans[].managementFeeFromPremiumPercent (strip trailing zeros and % sign)',
    '  שיעור דמי ניהול שנתי מחיסכון צבור → plans[].managementFeeFromSavingsPercent',
    '  תשואה מתחילת השנה → plans[].ytdReturnPercent (as a number, e.g. 3.33 not "3.33%")',
    '  הפקדה חודשית אחרונה - חוסך → plans[].lastMonthlyDepositEmployee',
    '  הפקדה חודשית אחרונה - מעסיק → plans[].lastMonthlyDepositEmployer',
    '  תאריך הפקדה אחרונה → plans[].lastDepositDate',
    '  מועד זכאות למשיכה בהטבת מס → plans[].withdrawalEligibilityDate (keep as string, e.g. "31/01/2028" or "ניתן למשיכה")',
    '  פנסיית נכות → plans[].disabilityPension (pension funds only)',
    '  תאריך פתיחת תכנית → plans[].joinDate',
    '  תאריך הצטרפות לראשונה → plans[].firstJoinDate',
    '  תאריך נכונות נתונים → plans[].dataAsOfDate',
    '',
    'The JSON MUST strictly conform to this TypeScript/Zod-style schema (no extra fields):',
    '',
    PensionExtractionSchema.toString(),
    '',
    'Rules:',
    '- For each column in the product tables under "פירוט המוצרים על פי סוג המוצר", you MUST create exactly one entry in the "plans" array.',
    '- Copy the "סטטוס" value for that column exactly. Do NOT infer status from any other section.',
    '- When copying numbers: copy digits exactly from the cell, remove only ₪ and thousands separators. Do NOT round, average, or estimate.',
    '- If a numeric value is missing or empty in the cell, use null.',
    '- If a string field is missing, use an empty string.',
    '- Dates: keep original format from the document (e.g. DD/MM/YYYY or MM/YYYY).',
    '- Do NOT provide explanations or additional keys.',
    '',
    'Here is the PDF text:',
    '---',
    '{TEXT}',
    '---',
  ].join('\n'),
  repairPromptTemplate:
    'Your previous JSON response failed schema validation. Errors:\n{ERRORS}\n\nPlease output only a single corrected JSON object that strictly conforms to the same schema. No explanations.',
};

